### ISSUE TITLE
ETSMoodleCoursesViewController.m line 79

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/ETSMobile-iOS#114]
#### in __55-[ETSMoodleCoursesViewController requestTokenAndUserID]_block_invoke

* Number of crashes: 96
* Impacted devices: 96

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/applets/ios/apps/ca.etsmtl.applets.etsmobile/issues/56365209f5d3a7f76b3f1317](https://fabric.io/applets/ios/apps/ca.etsmtl.applets.etsmobile/issues/56365209f5d3a7f76b3f1317)

**Comment by SamBellerose** [comment]
To fix this issue, we need to use a different context object that is not on the main thread.
