### ISSUE TITLE
Ajouter les partenaires

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-iOS#122]
Actuellement, la liste des partenaires d'ApplETS est hardcodée dans l'application.

Le call https://api3.clubapplets.ca/partners  renvoie la liste des partenaires en json, tenue à jour sur le site web.

Il faut dont réimplémenter la liste des partenaires fournie par l'API.

Pour donner une idée, voici comment ça a été fait sur ÉTSMobile-Android :

![etsmobile_ss_partenaire](https://cloud.githubusercontent.com/assets/1558361/12530308/80264292-c1a9-11e5-9cc5-760371d120b2.png)

**Comment by SamBellerose** [comment]
Les partenaires devront être Synchronisé dans la base de donnée. Tu auras à faire une migration de la base de donnée Core Data, j'ai déjà préparé le code pour ça, tu n'auras qu'à créer un nouveau model à partir de la version 2.
