### ISSUE TITLE
Corriger le calendrier ÉTS

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-iOS#129]
> Je voulais simplement vous signaler une petite erreur dans l'horaire de l'ÉTS présenté en vrac, dans l'application. Il y a une entrée "Reprise de la journée du lundi de Pâques vis-à-vis la date du 28 mars...qui EST la journée du lundi de Pâques. Ne devrions-nous pas y lire cette entrée vis-à-vis le 29 mars?

![image1](https://cloud.githubusercontent.com/assets/1558361/13624435/1df879ae-e57c-11e5-88a0-3825d48b706a.PNG)

**Comment by AlyssaBchk** [comment]
@sambellerose et moi avons déjà corrigé ce problème, il ne reste plus qu'à pousser ça.

**Comment by gnut3ll4** [comment]
S'agit-il du commit du 29 janvier ? 
https://github.com/ApplETS/ETSMobile-iOS/commit/909fdaaa9731f6fc5d3950d603b8995f84ddd435
Quel est votre échéancier à ce niveau ?
Êtes-vous capables de corriger avant Pâques pour les étudiants ?
