### ISSUE TITLE
Faire fonctionner radio Piranha.

### ISSUE THREAD

**Issue by SamBellerose** [ApplETS/ETSMobile-iOS#149]
Un étudiant a reporté qu'elle n'était plus fonctionnelle.

**Comment by AlyssaBk** [comment]
Réponse du dev de radio piranha :

"L'URL du stream mp3 a changé, vous pouvez télécharger le nouveau sur nouveau site de http://radiopiranha.com/ dans le .m3u il y à : http://live.radiopiranha.com:8000/radiopiranha.mp3

Si l'application mobile n'utilisait pas l'IP direct de la machine comme (142.137.247.95:8000/radiopiranha.mp3) mais bien l'ancienne redirection (radiopiranha.com:8000/radiopiranha.mp3) comme source alors c'est normal que ça ne fonctionne plus."
