### ISSUE TITLE
Ajouter les nouvelles d'Interface

### ISSUE THREAD

**Issue by gnut3ll4** [ApplETS/ETSMobile-iOS#20]
Élizabeth Le Sieur, du service aux étudiants, nous propose d'ajouter Interface dans nos actualités.
La plateforme interface dispose d'un flux RSS disponible ici : https://interfaceets.wordpress.com/feed/

**Comment by krazdax5** [comment]
Jva faire ça sur l'API pour qu'il n'y ait qu'un endpoint pour les nouvelles.
