### ISSUE TITLE
Ajouter le contrôle de Radio Piranha dans le control center

### ISSUE THREAD

**Issue by SamBellerose** [ApplETS/ETSMobile-iOS#22]

**Comment by Maxador** [comment]
J'ai essayé des trucs un peu. J'ai une idée de comment réussir mais le "playback menu" va être juste accessible dans l'application pour le moment et pas quand on retourne au "home screen".

[Documentation MPRemoteCommandCenter] (https://developer.apple.com/library/prerelease/ios/documentation/MediaPlayer/Reference/MPRemoteCommandCenter_Ref/index.html)

**Comment by krazdax5** [comment]
bizarre, ça devrait fontionner pourtant.

**Comment by jpmartin** [comment]
Non c'est normal que cela ne fonctionne pas avec la AVPLayer. Mais je viens de terminer le fix. La solution est celle que Max propose. Je commit à l'instant.

**Comment by krazdax5** [comment]
#fullLike

**Comment by SamBellerose** [comment]
Good job !
