### ISSUE TITLE
Today's Widget extension

### ISSUE THREAD

**Issue by Maxador** [ApplETS/ETSMobile-iOS#44]
J'avais comme idée d'ajouter un Widget à l'application pour pouvoir voir les cours qu'on a aujourd'hui. Au lieu de faire comme dans la version Android et de mettre ça comme page d'accueil, je pensais plutôt faire un Widget, comme ça l'utilisateur va pouvoir consulter ça avec les autres informations qu'il trouve utiles dans sa fenêtre de notification.

Je me le suis assigné à moi même parce que j'aimerais développer cette nouvelle fonctionnalité, je sais que ça pourrait être plus rapidement par d'autres (comme @jpmartin), mais ça me donnerais l'occasion d'apprendre un peu plus sur le Framework d'iOS.

[Inspiration](http://313e5987718b346aaf83-f5e825270f29a84f7881423410384342.r78.cf1.rackcdn.com/1413941028-2014-10-22-at-02-58-54-.jpeg)

**Comment by jpmartin** [comment]
Excellente idée. C’est sûr que je n’aurai pas le temps d'y toucher. Je te conseille de le faire pour la version 2.1 qui est pour iOS 8 seulement.

**Comment by Maxador** [comment]
Oh bon point, merci de m'en aviser.

**Comment by maxilapo** [comment]
Excellente idée !

2015-05-20 15:20 GMT-04:00 Maxime Mongeau <notifications@github.com>:
